import {IconPath, ImagePath} from '../assets';

export const HomeData = [
  {
    id: 1,
    firstTeam: 'Beaconsfield Town',
    imageFirstTeam: IconPath.teamfirst,
    scoreFirstTeam: '1',
    degree: '77',
    secondTeam: 'Hanwell Town',
    imageSecondTeam: IconPath.teamsecond,
    scoreSecondTam: '0',
    status: 'Live',
  },
  {
    id: 2,
    firstTeam: 'Beaconsfield Town',
    imageFirstTeam: IconPath.teamthird,
    scoreFirstTeam: '1',
    degree: '77',
    secondTeam: 'Hanwell Town',
    imageSecondTeam: IconPath.teamfour,
    scoreSecondTam: '0',
    status: 'Live',
  },
  {
    id: 3,
    firstTeam: 'Beaconsfield Town',
    imageFirstTeam: IconPath.teamfirst,
    scoreFirstTeam: '1',
    degree: '77',
    secondTeam: 'Hanwell Town',
    imageSecondTeam: IconPath.teamsecond,
    scoreSecondTam: '0',
    status: 'offline',
    time: '19:30',
    day: 'Today',
  },
  {
    id: 4,
    firstTeam: 'Beaconsfield Town',
    imageFirstTeam: IconPath.teamthird,
    scoreFirstTeam: '1',
    degree: '77',
    secondTeam: 'Hanwell Town',
    imageSecondTeam: IconPath.teamfour,
    scoreSecondTam: '0',
    status: 'Live',
  },
  {
    id: 5,
    firstTeam: 'Beaconsfield Town',
    imageFirstTeam: IconPath.teamfirst,
    scoreFirstTeam: '1',
    degree: '77',
    secondTeam: 'Hanwell Town',
    imageSecondTeam: IconPath.teamfour,
    scoreSecondTam: '0',
    status: 'offline',
    time: '19:30',
    day: 'Today',
  },
];

export const newsData = [
  {
    id: 1,
    title: `Manchester United 'extremely close' to signing Darwin Nunez`,
    subtitle:
      'The Benfica striker has been on the radar of a number of clubs ahead of the summer transfer window.',
    newstitle: 'Real madrid Official',

    descriptionfirst:
      'Manchester United are reportedly extremely close to completing the signing of Darwin Nunez.',
    descriptionsecond:
      'The 22-year-old Benfica striker has been in superb form this season, scoring 34 goals for the Portuguese outfit. His goal against Ajax in the Champions League will certainly have made an impression on newly-appointed United manager Erik ten Hag.',
    descriptionthird: `According to Give Me Sport journalist Dean Jones, a deal for Nunez would set United back £50.6m with Benfica having reportedly lined up Stuttgart's Sasa Kalajdzic as a replacement. Other reports have suggested that Benfica would be looking to cash in on the Uruguayan in order to fund their summer transfer window. Atletico Madrid are believed to be the only club likely to challenge United for Nunez.`,
    teamIcon: ImagePath.firstnews,
    time: '7 hours ago',
    icon: IconPath.teamfirst,
  },
  {
    id: 2,
    title: `Kane an inspiration for Spurs' squad, says Mason`,
    newstitle: 'Real madrid Official',
    teamIcon: ImagePath.secondnews,
    time: '30 min ago',
    descriptionfirst:
      'Manchester United are reportedly extremely close to completing the signing of Darwin Nunez.',
    descriptionsecond:
      'The 22-year-old Benfica striker has been in superb form this season, scoring 34 goals for the Portuguese outfit. His goal against Ajax in the Champions League will certainly have made an impression on newly-appointed United manager Erik ten Hag.',
    descriptionthird: `According to Give Me Sport journalist Dean Jones, a deal for Nunez would set United back £50.6m with Benfica having reportedly lined up Stuttgart's Sasa Kalajdzic as a replacement. Other reports have suggested that Benfica would be looking to cash in on the Uruguayan in order to fund their summer transfer window. Atletico Madrid are believed to be the only club likely to challenge United for Nunez.`,
    icon: IconPath.teamsecond,
  },
  {
    id: 3,
    title: `Kane an inspiration for Spurs' squad, says Mason`,
    newstitle: 'Real madrid Official',
    teamIcon: ImagePath.firstnews,
    time: '50 min ago',

    descriptionfirst:
      'Manchester United are reportedly extremely close to completing the signing of Darwin Nunez.',
    descriptionsecond:
      'The 22-year-old Benfica striker has been in superb form this season, scoring 34 goals for the Portuguese outfit. His goal against Ajax in the Champions League will certainly have made an impression on newly-appointed United manager Erik ten Hag.',
    descriptionthird: `According to Give Me Sport journalist Dean Jones, a deal for Nunez would set United back £50.6m with Benfica having reportedly lined up Stuttgart's Sasa Kalajdzic as a replacement. Other reports have suggested that Benfica would be looking to cash in on the Uruguayan in order to fund their summer transfer window. Atletico Madrid are believed to be the only club likely to challenge United for Nunez.`,
    icon: IconPath.teamthird,
  },
  {
    id: 4,
    title: `Kane an inspiration for Spurs' squad, says Mason`,
    newstitle: 'Real madrid Official',
    teamIcon: ImagePath.secondnews,
    time: '55 min ago',

    descriptionfirst:
      'Manchester United are reportedly extremely close to completing the signing of Darwin Nunez.',
    descriptionsecond:
      'The 22-year-old Benfica striker has been in superb form this season, scoring 34 goals for the Portuguese outfit. His goal against Ajax in the Champions League will certainly have made an impression on newly-appointed United manager Erik ten Hag.',
    descriptionthird: `According to Give Me Sport journalist Dean Jones, a deal for Nunez would set United back £50.6m with Benfica having reportedly lined up Stuttgart's Sasa Kalajdzic as a replacement. Other reports have suggested that Benfica would be looking to cash in on the Uruguayan in order to fund their summer transfer window. Atletico Madrid are believed to be the only club likely to challenge United for Nunez.`,
    icon: IconPath.teamfour,
  },
  {
    id: 5,
    title: `Kane an inspiration for Spurs' squad, says Mason`,
    newstitle: 'Real madrid Official',
    teamIcon: ImagePath.secondnews,
    time: '1 hour ago',

    descriptionfirst:
      'Manchester United are reportedly extremely close to completing the signing of Darwin Nunez.',
    descriptionsecond:
      'The 22-year-old Benfica striker has been in superb form this season, scoring 34 goals for the Portuguese outfit. His goal against Ajax in the Champions League will certainly have made an impression on newly-appointed United manager Erik ten Hag.',
    descriptionthird: `According to Give Me Sport journalist Dean Jones, a deal for Nunez would set United back £50.6m with Benfica having reportedly lined up Stuttgart's Sasa Kalajdzic as a replacement. Other reports have suggested that Benfica would be looking to cash in on the Uruguayan in order to fund their summer transfer window. Atletico Madrid are believed to be the only club likely to challenge United for Nunez.`,
    icon: IconPath.teamfirst,
  },
];

export const resultData = [
  {
    id: 1,
    titleplayer: 'Premier League',
    teamname: 'England',
    icon: ImagePath.resulticonsecond,
    data: [
      {
        id: 1,
        teamfirst: 'Manchester City',
        teamfirstIcon: ImagePath.resulticon,
        teamscore: '1',
        teamsecond: 'Brighton',
        teamsecondIcon: ImagePath.resulticonsecond,
        teamsecondscore: '2',
        teamdegree: '85',
      },
      {
        id: 2,
        teamfirst: 'Arsenal',
        teamfirstIcon: ImagePath.resulticonfirst,
        teamsecond: 'Burnley',
        teamsecondIcon: ImagePath.resulticonsecond,
        status: 'Live',
        time: '20:00',
        day: 'Today',
      },
      {
        id: 3,
        teamfirst: 'Aston Villa',
        teamfirstIcon: ImagePath.resulticonfour,
        teamscore: '2',
        teamsecond: 'Brentford',
        teamsecondIcon: ImagePath.resulticonfive,
        teamsecondscore: '1',
        teamdegree: '77',
      },
    ],
  },
  {
    id: 2,
    titleplayer: 'La Liga',
    teamname: 'Spain',
    icon: ImagePath.resulticonthird,
    data: [
      {
        id: 1,
        teamfirst: 'Real Madrid',
        teamfirstIcon: ImagePath.resulticonsix,
        teamscore: '1',
        teamsecond: 'Brighton',
        teamsecondIcon: ImagePath.resulticonseven,
        teamsecondscore: '2',
        teamdegree: '85',
      },
      {
        id: 2,
        teamfirst: 'Barcelona',
        teamfirstIcon: ImagePath.resulticoneight,
        teamsecond: 'Burnley',
        teamsecondIcon: ImagePath.resulticonnine,
        status: 'Live',
        time: '6:00',
        day: 'Today',
      },
      {
        id: 3,
        teamfirst: 'Sevilla',
        teamfirstIcon: ImagePath.resulticonfour,
        teamsecond: 'Atletico Madrid',
        teamsecondIcon: ImagePath.resulticonfive,
        status: 'Live',
        time: '6:00',
        day: 'Tomorrow',
      },
      {
        id: 4,
        teamfirst: 'Villareal',
        teamfirstIcon: ImagePath.resulticonten,
        teamscore: '0',
        teamsecond: 'Valencia',
        teamsecondIcon: ImagePath.resulticoneleven,
        teamsecondscore: '1',
        teamdegree: '52',
      },
    ],
  },
  {
    id: 3,
    titleplayer: 'Premier League',
    teamname: 'England',
    icon: ImagePath.resulticonsecond,
    data: [
      {
        id: 1,
        teamfirst: 'Manchester City',
        teamfirstIcon: ImagePath.resulticon,
        teamscore: '1',
        teamsecond: 'Brighton',
        teamsecondIcon: ImagePath.resulticonsecond,
        teamsecondscore: '2',
        teamdegree: '85',
      },
      {
        id: 2,
        teamfirst: 'Arsenal',
        teamfirstIcon: ImagePath.resulticonfirst,
        teamsecond: 'Burnley',
        teamsecondIcon: ImagePath.resulticonsecond,
        status: 'Live',
        time: '20:00',
        day: 'Today',
      },
      {
        id: 3,
        teamfirst: 'Aston Villa',
        teamfirstIcon: ImagePath.resulticonfour,
        teamscore: '2',
        teamsecond: 'Brentford',
        teamsecondIcon: ImagePath.resulticonfive,
        teamsecondscore: '1',
        teamdegree: '77',
      },
    ],
  },
];
